name = "newsletter"
description = "A theme used at u9h.design with a focus on readable content."
license = "MIT"
homepage = "https://github.com/u9h/newsletter"
min_version = "0.4.1"

[extra]
[extra.newsletter]
cms = true
logo = "/media/default_logo.png"
menu = [ 
    {url = "/blog", name = "Blog"},
    {url = "mailto:alex@u9h.design", name = "Contact"}
]

[extra.newsletter.home]
header = "More than just design."
subheader = "We are a fully-digital design studio committed to transparency and creativity."

[extra.newsletter.blog]
nav_background = "/media/default_pattern"
menu = [
]