name = "newsletter"
description = "A theme used at u9h.design with a focus on readable content."
license = "MIT"
homepage = "https://github.com/u9h/newsletter"
min_version = "0.3.4"

[extra]
feather_header_image = "/theme_images/default.gif"
feather_disqus_code = ""
feather_donate_link = ""
feather_analytics = ""

[author]
name = "doomy"
homepage = "https://alexanderlozada.com"